# Generated by Django 4.2.3 on 2023-07-07 14:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_avatar', models.ImageField(upload_to='avatars/')),
                ('users_lies', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('texte', models.TextField()),
                ('image_illustration', models.ImageField(upload_to='blogposts/')),
                ('date_post', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('promo', models.BooleanField(default=False)),
                ('pourcentage_promo', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('statut_commande', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blog_post_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('texte', models.TextField()),
                ('user_auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfosQDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('slogan_site', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partenaires/')),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('image_1', models.ImageField(upload_to='produits/')),
                ('image_2', models.ImageField(upload_to='produits/')),
                ('image_3', models.ImageField(upload_to='produits/')),
                ('image_4', models.ImageField(upload_to='produits/')),
                ('image_5', models.ImageField(upload_to='produits/')),
                ('image_6', models.ImageField(upload_to='produits/')),
                ('marque_vendeur', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('gélules', 'Gélules'), ('poudre', 'Poudre')], max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('macronutriments', models.TextField()),
                ('variations', models.CharField(max_length=255)),
                ('en_promo', models.BooleanField(default=False)),
                ('pourcentage_promo', models.PositiveIntegerField(blank=True, null=True)),
                ('prix_normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantite_stock', models.PositiveIntegerField()),
                ('date_ajout_produit_db', models.DateField(auto_now_add=True)),
                ('date_ajout_panier_user', models.DateField(blank=True, null=True)),
                ('date_ajout_wishlist_user', models.DateField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorie')),
                ('commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.commentaires')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('membre', 'Membre'), ('webmaster', 'Webmaster'), ('stock', 'Stock')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metiers_hobbies', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('image_banniere_profil', models.ImageField(upload_to='bannieres/')),
                ('abonne_newsletter', models.BooleanField(default=False)),
                ('avatar_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.avatar')),
                ('commandes_passees', models.ManyToManyField(to='shop.commandes')),
                ('contacts_echanges', models.ManyToManyField(to='shop.contacts')),
                ('produits_panier', models.ManyToManyField(related_name='paniers', to='shop.produits')),
                ('produits_wishlist', models.ManyToManyField(related_name='wishlists', to='shop.produits')),
                ('role', models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.roles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produits_ajoutes', models.ManyToManyField(to='shop.produits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.userextension')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('blog_posts_lies', models.ManyToManyField(to='shop.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_moyenne', models.DecimalField(decimal_places=1, max_digits=2)),
                ('produit_ou_blogpost_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.produits')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pourcentage_promo', models.PositiveIntegerField()),
                ('slogan', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_illustration', models.ImageField(upload_to='promotions/')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('categorie_en_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.categorie')),
                ('produit_en_promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.produits')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsCommandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.commandes')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produits')),
            ],
        ),
        migrations.AddField(
            model_name='produits',
            name='nature_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.promotions'),
        ),
        migrations.AddField(
            model_name='produits',
            name='review_produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.review'),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ajoutee', models.PositiveIntegerField()),
                ('produit_inclus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produits')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.userextension')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commentaires',
            name='produit_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.produits'),
        ),
        migrations.AddField(
            model_name='commentaires',
            name='reponse_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.commentaires'),
        ),
        migrations.AddField(
            model_name='commentaires',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commandes',
            name='produits_commandes',
            field=models.ManyToManyField(through='shop.ProduitsCommandes', to='shop.produits'),
        ),
        migrations.AddField(
            model_name='commandes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorie'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='commentaires_lies',
            field=models.ManyToManyField(to='shop.commentaires'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='review_blogpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.review'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='user_auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
