# Generated by Django 4.2.3 on 2023-07-17 19:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('metiers_hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image_banniere_profil', models.ImageField(blank=True, null=True, upload_to='bannieres/')),
                ('abonne_newsletter', models.BooleanField(default=False)),
                ('promo_code_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('texte', models.TextField()),
                ('image_illustration', models.ImageField(upload_to='blogposts/')),
                ('date_post', models.DateField(auto_now_add=True)),
                ('date_modification', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_illustration', models.ImageField(upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Commandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField()),
                ('statut_commande', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.commentaires')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InfosQDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('slogan_site', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='partenaires/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('image_1', models.ImageField(upload_to=shop.models.upload_to_product)),
                ('image_2', models.ImageField(upload_to=shop.models.upload_to_product)),
                ('image_3', models.ImageField(upload_to=shop.models.upload_to_product)),
                ('image_4', models.ImageField(upload_to=shop.models.upload_to_product)),
                ('image_5', models.ImageField(upload_to=shop.models.upload_to_product)),
                ('marque_vendeur', models.CharField(choices=[('MyProtein', 'MyProtein'), ('Prozis', 'Prozis'), ('HSN', 'HSN'), ('Optimum Nutrition', 'Optimum Nutrition'), ('MuscleTech', 'MuscleTech'), ('Dymatize', 'Dymatize'), ('Cellucor', 'Cellucor'), ('MusclePharm', 'MusclePharm'), ('Universal Nutrition', 'Universal Nutrition')], max_length=255)),
                ('type', models.CharField(choices=[('capsules', 'Capsules'), ('powder', 'Powder')], max_length=255)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('macronutriments', models.TextField()),
                ('date_ajout_produit_db', models.DateField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorie')),
                ('commentaire', models.ManyToManyField(blank=True, to='shop.commentaires')),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pourcentage_promo', models.PositiveIntegerField()),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('image_illustration', models.ImageField(upload_to='promotions/')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('membre', 'Membre'), ('webmaster', 'Webmaster'), ('stock', 'Stock')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Variantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(blank=True, choices=[('250g', '250g'), ('500g', '500g'), ('1kg', '1kg'), ('2kg', '2kg'), ('30 capsules', '30 capsules'), ('60 capsules', '60 capsules'), ('90 capsules', '90 capsules'), ('120 capsules', '120 capsules')], max_length=255)),
                ('produits', models.ManyToManyField(blank=True, related_name='variante_produits', through='shop.ProductVariant', to='shop.produits')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('blog_posts_lies', models.ManyToManyField(to='shop.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsCommandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.commandes')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='produits',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.promotions'),
        ),
        migrations.AddField(
            model_name='produits',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='produit_variations', through='shop.ProductVariant', to='shop.variantes'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.produits'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.variantes'),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ajoutee', models.PositiveIntegerField()),
                ('produit_inclus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_promo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.promotions')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('texte', models.TextField(null=True)),
                ('lu_par_admin', models.BooleanField(default=False)),
                ('user_auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commandes',
            name='produits_commandes',
            field=models.ManyToManyField(through='shop.ProduitsCommandes', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='commandes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorie',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promotions'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorie'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='commentaires_lies',
            field=models.ManyToManyField(to='shop.commentaires'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='user_auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='commandes_passees',
            field=models.ManyToManyField(blank=True, related_name='commandes', to='shop.commandes'),
        ),
        migrations.AddField(
            model_name='user',
            name='contacts_echanges',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='shop.contacts'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='produits_panier',
            field=models.ManyToManyField(blank=True, related_name='paniers', to='shop.productvariant'),
        ),
        migrations.AddField(
            model_name='user',
            name='produits_wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='shop.produits'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.roles'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant')},
        ),
    ]
