# Generated by Django 4.2.3 on 2023-07-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantes',
            name='produits',
            field=models.ManyToManyField(blank=True, related_name='variante_produits', through='shop.ProductVariant', to='shop.produits'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='produit_variations', through='shop.ProductVariant', to='shop.variantes'),
        ),
    ]
