# Generated by Django 4.2.3 on 2023-07-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='review_blogpost',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='review_produit',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
