# Generated by Django 4.2.3 on 2023-07-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitscommandes',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
