# Generated by Django 4.2.3 on 2023-07-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productvariant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantite_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
