# Generated by Django 4.2.3 on 2023-07-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_variantes_produits_alter_produits_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='quantite_stock',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'variant')},
        ),
    ]
