# Generated by Django 4.2.3 on 2023-07-13 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productvariant_quantite_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantes',
            name='contenu',
            field=models.CharField(blank=True, choices=[('250g', '250g'), ('500g', '500g'), ('1kg', '1kg'), ('2kg', '2kg'), ('30 capsules', '30 capsules'), ('60 capsules', '60 capsules'), ('90 capsules', '90 capsules'), ('120 capsules', '120 capsules')], max_length=255),
        ),
    ]
