# Generated by Django 4.2.3 on 2023-07-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_extrapromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
