# Generated by Django 4.2.3 on 2023-07-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_productvariant_quantite_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
