# Generated by Django 4.2.3 on 2023-07-13 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productvariant_prix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produits',
            old_name='nature_promo',
            new_name='promo',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='en_promo',
        ),
        migrations.RemoveField(
            model_name='produits',
            name='pourcentage_promo',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='categorie_en_promo',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='produit_en_promo',
        ),
        migrations.AlterField(
            model_name='categorie',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promotions'),
        ),
    ]
