# Generated by Django 4.2.3 on 2023-07-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_user_contacts_echanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='prix_total',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
