# Generated by Django 4.2.3 on 2023-07-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_avatar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_lie',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
