# Generated by Django 4.2.3 on 2023-07-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_nature_promo_produits_promo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='pourcentage_promo',
        ),
    ]
