# Generated by Django 4.2.3 on 2023-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_conversation_remove_produits_date_ajout_panier_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='user_repondant',
        ),
        migrations.AddField(
            model_name='contacts',
            name='lu_par_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
