# Generated by Django 4.2.3 on 2023-07-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_commandes_prix_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitscommandes',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
