# Generated by Django 4.2.3 on 2023-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_contacts_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='promo_code_used',
            field=models.BooleanField(default=False),
        ),
    ]
