# Generated by Django 4.2.3 on 2023-07-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_panier_promo_code_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='promo_code_used',
        ),
        migrations.AddField(
            model_name='user',
            name='promo_code_used',
            field=models.BooleanField(default=False),
        ),
    ]
