# Generated by Django 4.2.3 on 2023-07-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_commandes_prix_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaires',
            name='texte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produitscommandes',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
