# Generated by Django 4.2.3 on 2023-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_commentaires_texte_alter_produitscommandes_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_banniere_profil',
            field=models.ImageField(blank=True, default='bannieres/default-banner.webp', null=True, upload_to='bannieres/'),
        ),
    ]
