# Generated by Django 4.2.3 on 2023-07-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_newsletter_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='tags',
            name='blog_posts_lies',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(to='shop.tags'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categoriesblog'),
        ),
    ]
