# Generated by Django 4.2.3 on 2023-07-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_categoriesblog_remove_tags_blog_posts_lies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='user_auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
