# Generated by Django 4.2.3 on 2023-07-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_blogpost_user_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.tags'),
        ),
    ]
