# Generated by Django 4.2.3 on 2023-07-18 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_blogpost_commentaires_lies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='date_modification',
        ),
    ]
