# Generated by Django 4.2.3 on 2023-07-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_blogpost_date_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='commentaires',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='date_ajout_produit_db',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
