# Generated by Django 4.2.2 on 2023-07-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_commandes_date_commande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaires',
            name='user',
        ),
        migrations.AddField(
            model_name='commentaires',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='commentaires',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
