# Generated by Django 4.2.2 on 2023-07-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_commentaires_user_commentaires_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaires',
            name='reponse_a',
        ),
    ]
