# Generated by Django 4.2.3 on 2023-07-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_commentaires_reponse_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
